### ISSUE TITLE
# ERRORs: "Loading required package: sp" "there is no package called ‘sp’"

### ISSUE THREAD

**Issue by moko-moko** [kbroman/RqtlWorkshop#1]
I try your tutorial of "A shorter tour of R/qtl (rqtltour2.pdf)".

> nind(sug)
[1] 163
Loading required package: sp
> nchr(sug)
[1] 19
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘sp’

What happened? 
It would be greatly appreciated if you could explain the details.

**Comment by kbroman** [comment]
Hmm; strange. I've never seen this, and I unfortunately have no idea why it would occur. The [sp package](https://cran.r-project.org/package=sp) is for spatial data, and has no relation to R/qtl. I don't understand why R would be trying to load the sp package.

What other packages do you have loaded? Type `sessionInfo()` to see.

**Comment by mohammed-abdulrahman** [comment]
Thanks kbroman for this platform. I am getting the error: Error in inla.call.builtin() : INLA installation error; no such file
Also I am getting at the start of R the error: Loading required package: sp
Please help me to fix them.

**Comment by kbroman** [comment]
@mohammed-abdulrahmen Could you use copy-paste to show exactly what you’re typing, and the exact error messages?

**Comment by mohammed-abdulrahman** [comment]
# install libraries (only once)
# install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
# install.packages(c("haven","readxl"))

# read data
regions<-read.table(".../regions.txt",header=TRUE) # contains names of regions and id
DATA <- read.csv(".../sudancancer_top5th.csv")
n<-dim(DATA)[1]

# match region id to location
DATA$region<-NA
for (i in 1:18)
  DATA$region[as.character(DATA$STATE)==as.character(regions$LOCATION[i])]<-regions$id[i]
table(DATA$STATE)
table(DATA$region)

# read population files
library(readxl)
population0<-array(NA,c(18,17,2)) # regions x agegroups x years x gender
popfile<-read_excel(paste0(".../POPULATION_2013.xlsx"))
for (i in 1:dim(popfile)[1])
{
  population0[which(popfile$STATE[i]==regions$LOCATION),     # region
              as.numeric(substr(popfile$AGEGROUP[i],0,2))/5+1,  # agegroup
              1] <- popfile$MALE[i]
  population0[which(popfile$STATE[i]==regions$LOCATION),     # region
              as.numeric(substr(popfile$AGEGROUP[i],0,2))/5+1,  # agegroup
              2] <- popfile$FEMALE[i]
}

population<-array(NA,c(18,4,2)) # regions x agegroups x gender
population[,1,]<-apply(population0[,1:3,],c(1,3),sum)
population[,2,]<-apply(population0[,4:9,],c(1,3),sum)
population[,3,]<-apply(population0[,10:13,],c(1,3),sum)
population[,4,]<-apply(population0[,14:17,],c(1,3),sum)


#find cancer types
DATA$CANCER<-factor(DATA$CANCER)
summary(DATA$CANCER)
cancertypes<-levels(DATA$CANCER)


# INLA graph, defines neighbours of regions
library(INLA)
inla.spy(".../sudan16.graph")
graph<-inla.read.graph(".../sudan16.graph")

# file with borders
# only once:
# url="https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_SDN_1_sp.rds"
# download.file(url,destfile="gadm36_SDN_1_sp.rds")
rds<-readRDS(".../gadm36_SDN_1_sp.rds")

rds16<-rds[-c(16,17)]
## match region id to regions in rds
id<-1:18
for (i in 1:18)
  id[i]<-which(regions$rds==i)
# check: the following lists should be the same
# print(regions$LOCATION[id])
# print(rds$NAME_1)

for (g in 1:2)
  for (a in 1:4)
    for (c in cancertypes)
      poptotal<-sum(DATA$popnew[DATA$AGECACODE==a&DATA$GENDERCODE==g&DATA$CANCER==c,])


# add E to dataset
DATA$popnew <- rep(NA,n)
for (i in 1:n)
{
  DATA$popnew[i]<-population[DATA$region[i], DATA$AGECACODE[i], DATA$GENDERCODE[i]]
}

# compute expected cases (E)

DATA$E <- rep(NA,n)
for (a in 1:4)
  for (g in 1:2)
    for (c in 1:5)
    {
      countsum<-sum(DATA$COUNT[DATA$CANCODE==c&DATA$AGECACODE==a&DATA$GENDERCODE==g])
      popsum<-sum(DATA$popnew[DATA$CANCODE==c&DATA$AGECACODE==a&DATA$GENDERCODE==g])
      DATA$E[DATA$CANCODE==c&DATA$AGECACODE==a&DATA$GENDERCODE==g]<-DATA$popnew[DATA$CANCODE==c&DATA$AGECACODE==a&DATA$GENDERCODE==g]/popsum*countsum
    }

# remove region 17 and 18
DATA$region16 <- DATA$region

DATA$region16[DATA$region==18]<-16

for (c in 1:5)
  for (g in 1:2)
  {
    data<-DATA[DATA$CANCODE==c&DATA$GENDERCODE==g,]
    
    #INLA
    library(INLA)
    model<-inla(COUNT~
                  f(region16, model="besag",graph=graph,adjust.for.con.comp = TRUE,scale.model = FALSE)
                +f(AGECACODE, model="iid"), 
                family="poisson", data=data, E=E, verbose=TRUE)
    result.region<-model$summary.random$region16
    no16<-c(16,rep(0,7))
    no17<-c(16,rep(0,7))
    names(no16)<-names(no17)<-names(result.region)
    result.region<-rbind(result.region[1:15,],no16,no17,result.region[16,])
    result.region$ID[18]=18
    result.ag<-model$summary.random$AGECACODE
    
    # plot result
    library(SpatialEpi)
    
    pdf(paste0("../plots_dec18/",c,"_",g,".pdf"))
    par(mfrow=c(2,1))
    
    mapvariable(result.region$mean, rds, main="Estimated spatial effect (Bayesian model)")
    
    ylim<-c(min(result.ag$`0.025quant`),max(result.ag$`0.975quant`))
    plot(result.ag$mean,type="l",xlab="age group",ylab="",ylim=ylim,axes=FALSE)
    lines(result.ag$`0.025quant`,lty=2)
    lines(result.ag$`0.975quant`,lty=2)
    lines(1:17,rep(0,17),lty=1,lwd=0.5, col=grey(0.75))
    axis(1,at=1:17,labels=c(paste0(seq(0,75,5),"-",seq(4,79,5)),"80+"))
    axis(2)
    box()
    title(main=paste0(c, " ", g," (n=",sum(data$count,na.rm=TRUE),")"))
    dev.off()
  }

**Comment by mohammed-abdulrahman** [comment]
Thanks for your response the above is the code.

**Comment by mohammed-abdulrahman** [comment]
Error: package ‘sp’ required by ‘INLA’ could not be found

**Comment by kbroman** [comment]
@mohammed-abdulrahman As mentioned above, try `install.packages("sp")`

But neither the sp package nor INLA are required by [R/qtl](http://rqtl.org), and so it's not clear what relationship that has to this R/qtl workshop repository.

**Comment by mohammed-abdulrahman** [comment]
Thanks all... 
The problem is which should be installed first? INLA or sp>>>
Now it's working...
